config/routes.rb
Rails.application.routes.draw do
  root to: "pages#dashboard"
  get "dashboards", to: "pages#dashboard"
  get "past_dashboards", to: "pages#past_dashboard"
  get "secret_spots", to: "pages#secret_spot"
  devise_for :users

  resources :travels
  resources :travel_tags, only: [:new, :create]
  resources :trav_trav_type_tags, only: [:new, :create]

  resources :places
  resources :place_traveler_type_tags, only: [:index, :new, :create, :destroy]
  resources :place_tags, only: [:index, :new, :create, :destroy]

  get "travels/:id/map", to: "travels#map", as: :travel_map

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
         <i onclick="history.back()" class="fa-solid fa-chevron-left nav-icon"></i>
    <%= link_to dashboards_path, class: "navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/dwl5s1v4k/image/upload/v1687711356/Rectangle_11_pbq5cu.png", class: "logo" %>
    <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-itam">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu", crop: :fill %>
            <% end %>
            </a>
          </li>

          <li class="nav-itam active", id="normal">
            <i class="fa-solid fa-house nav-icon"></i>
            <%= link_to "Accueil", dashboards_path, class: "nav-link" %>
          </li>

          <li class="nav-itam", id="normal">
            <i class="fa-solid fa-user-secret nav-icon"></i>
            <%= link_to "Secret Spot", secret_spots_path, class: "nav-link" %>
          </li>

          <% if current_user.admin? %>
            <li class="nav-itam", id="normal">
              <i class="fa-solid fa-check nav-icon"></i>
              <%= link_to "Places en attente de validation", places_path, class: "nav-link" %>
            </li>
          <% end %>

          <li class="nav-itam", id="normal">
            <i class="fa-solid fa-arrow-right-from-bracket nav-icon">
            </i> <%= button_to "Déconnexion", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>