config/routes.rb
Rails.application.routes.draw do
  root to: "pages#dashboard"
  get "dashboards", to: "pages#dashboard"
  get "past_dashboards", to: "pages#past_dashboard"
  get "secret_spots", to: "pages#secret_spot"
  devise_for :users

  resources :travels
  resources :travel_tags, only: [:new, :create]
  resources :trav_trav_type_tags, only: [:new, :create]

  resources :places
  resources :place_traveler_type_tags, only: [:index, :new, :create, :destroy]
  resources :place_tags, only: [:index, :new, :create, :destroy]

  get "travels/:id/map", to: "travels#map", as: :travel_map

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/dashboard.html.erb
<div class="d-flex">
  <%= link_to dashboards_path, class: "btn-voyage" do %>
  Mes voyages
  <% end %>
  <%= link_to past_dashboards_path, class: "btn-histo" do %>
  Mon historique
  <% end %>
</div>

<% @future_travels.each do |travel| %>
  <%= link_to travel_path(travel), class: "travel-card" do %>
    <div class="rectangle">
      <% if travel.places.first != nil %>
        <%= cl_image_tag travel.places.first.photos.first.key, height: 350, width: 450, crop: :fill %>
      <% else %>
        <%= image_tag "https://res.cloudinary.com/dwl5s1v4k/image/upload/v1688474864/photo-non-disponible-1_do68va.jpg", height: 350, width: 450, crop: :fill %>
      <% end %>
      <div>
        <h2><%= travel.name %></h2>
        Dates :
        <div>
          <strong><%= travel.beginning_date %></strong>  -  <strong><%= travel.ending_date %></strong>
        </div>
        Prix : <strong><%= travel.places.sum(&:price) %> €</strong>
      </div>
    </div>
  <% end %>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/past_dashboard.html.erb
<div class="container"></div>
<div class="container_chocolat"></div>
<div class="d-flex">
<%= link_to dashboards_path, class: "btn-histo" do %>
Mes voyages
<% end %>
<%= link_to past_dashboards_path, class: "btn-voyage" do %>
Mon historique
<% end %>
</div>

<% @past_travels.each do |travel| %>
  <%= link_to travel_path(travel), class: "travel-card" do %>
    <div class="rectangle">
        <% if travel.places.first != nil %>
          <%= cl_image_tag travel.places.first.photos.first.key, height: 350, width: 450, crop: :fill %>
        <% else %>
          <%= image_tag "https://res.cloudinary.com/dwl5s1v4k/image/upload/v1688474864/photo-non-disponible-1_do68va.jpg", height: 350, width: 450, crop: :fill %>
        <% end %>
        <div>
          <h2><%= travel.name %></h2>
          Dates :
          <div>
            <strong><%= travel.beginning_date %></strong>  -  <strong><%= travel.ending_date %></strong>
          </div>
          Prix : <strong><%= travel.places.sum(&:price) %> €</strong>
        </div>
    </div>
  <% end %>
<% end %>

app/views/pages/secret_spot.html.erb
<div class="container"></div>
<div class="container_chocolat"></div>
<h2 class ="titresecret">Mes Secret Spots 🤫</h2>
<br>
<%# <h6>À venir</h6>
<h6 class ="passés"> Passés</h6> %>
<% @my_secrets.each do |secret| %>
  <%= link_to place_path(secret), class: "travel-card" do %>
      <div class="rectangle">
          <% if secret.photos.attached? %>
            <% secret.photos.each do |photo| %>
              <%= cl_image_tag photo.key, height: 350, width: 450, crop: :fill %>
              <% break %>
            <% end %>
          <% else %>
          <%= image_tag "https://res.cloudinary.com/dwl5s1v4k/image/upload/v1688474864/photo-non-disponible-1_do68va.jpg", height: 350, width: 450, crop: :fill %>
          <% end %>
          <div>
            <h2><%= secret.name %></h2>
            <% if secret.validation? %>
              <%= secret.description.first(60) ... %>
            <% else %>
              <h3 class="att-validation">En attente de validation</h3>
            <% end %>
          </div>
      </div>

  <% end %>
<% end %>