config/routes.rb
Rails.application.routes.draw do
  root to: "pages#dashboard"
  get "dashboards", to: "pages#dashboard"
  get "past_dashboards", to: "pages#past_dashboard"
  get "secret_spots", to: "pages#secret_spot"
  devise_for :users

  resources :travels
  resources :travel_tags, only: [:new, :create]
  resources :trav_trav_type_tags, only: [:new, :create]

  resources :places
  resources :place_traveler_type_tags, only: [:index, :new, :create, :destroy]
  resources :place_tags, only: [:index, :new, :create, :destroy]

  get "travels/:id/map", to: "travels#map", as: :travel_map

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user

  has_many :steps, dependent: :destroy
  has_many :travels, through: :steps

  has_many :place_trav_taggings, dependent: :destroy
  has_many :place_traveler_type_tags, through: :place_trav_taggings

  has_many :place_taggings, dependent: :destroy
  has_many :place_tags, through: :place_taggings

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10, maximum: 800 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :duration, presence: true, numericality: { greater_than: 0 }
  validates :address, presence: true
  geocoded_by :address
  has_many_attached :photos
  after_validation :geocode, if: :will_save_change_to_address?


  def self.find_for_travel(travel)
    valid_places = all.where(validation: true)
    near_places = valid_places.near(travel.starting_point, 10)
    selected_secret_places = filter_for_secret_spots(near_places, travel.incl_secret)
    # separer les places en 2 listes, local ou touristique et pick dans chaque liste en fonction du pourcentage choisi par le user.
    selected_trav_places = filter_for_traveler_tags(near_places, travel.trav_trav_type_tags)
    selected_places = filter_for_tags(selected_trav_places, travel.travel_tags)
    selected_price_places = filter_for_price(selected_places, travel.budget)
    return filter_for_time(selected_price_places, travel.start_hour, travel.end_hour)
  end

  def self.filter_for_secret_spots(places_to_filter, secret_spot)
    @selected_places = []
    if secret_spot
      @selected_places << places_to_filter
    else
      places_to_filter.each do |place|
        if !place.secret_spot
          @selected_places << place
        end
      end
    end
    return @selected_places
  end

  def self.filter_for_traveler_tags(places_to_filter, traveler_tags)
    @travel_traveler_tags = traveler_tags.flat_map { |traveler_tag| traveler_tag }
    @travel_traveler_tag = TravTravTypeTag.where(id: @travel_traveler_tags.pluck(:id))
    @travel_traveler_tag_name = @travel_traveler_tag.map { |travel_tag_name| travel_tag_name.name }

    @selected_places = []

    places_to_filter.each do |place|
      if place.place_traveler_type_tags.pluck(:tag).include?(@travel_traveler_tag_name.join)
        @selected_places << place
      end
    end
    # @selected_places << places_to_filter.select { |place| place.place_traveler_type_tags.pluck(:tag).include?(@travel_traveler_tag_name) }

    @selected_places.flatten!
    @selected_places.uniq!
    return @selected_places
  end

  def self.filter_for_tags(places_to_filter, tags)
    @travel_tags = tags.flat_map { |travel_tag| travel_tag }
    @travel_tag = TravelTag.where(id: @travel_tags.pluck(:id))
    @travel_tag_names = @travel_tag.map { |tag_name| tag_name.name }

    @selected_places = []

    @travel_tag_names.each do |tag_name|
      @selected_places << places_to_filter.select { |place| place.place_tags.pluck(:name).include?(tag_name) }
    end

    @selected_places.flatten!
    @selected_places.uniq!
    return @selected_places
  end


  def self.filter_for_price(places_to_filter, budget)
    sorted_places = places_to_filter.sort_by(&:price)
    selected_places = []
    total_price = 0
    sorted_places.each do |place|
      if (total_price + place.price) <= budget
        selected_places << place
        total_price += place.price
      else
        break
      end
    end
    return selected_places
  end

  def self.filter_for_time(places_to_filter, start_time, end_time)
    sorted_places = places_to_filter.sort_by(&:duration)
    day_duration = (end_time - start_time) / 60 # passer de secondes à minutes
    selected_places = []
    total_duration = 0
    sorted_places.each do |place|
      if (total_duration + place.duration) <= day_duration
        selected_places << place
        total_duration += place.duration
      else
        break
      end
    end
    return selected_places
  end

  # def self.filter_for_touristic(places_to_filter, touristic, touristic_range)
  #   touristic_place = []
  #   local_place = []
  #   selected_places = []
  #   places_to_filter.each do |place|
  #     if place.touristic
  #       touristic_place << place
  #     else
  #       local_place << place
  #     end

  #   end
  #   return selected_places
  # end


  # def self.filter_for_days(places_to_filter, beg_date, end_date)
  #   nb_days = (end_date - beg_date)
  # end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  def index
    @places = policy_scope(Place)
    @markers = @places.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {place: place})
      }
    end
    authorize @places
  end

  def show
    @marker = [{ lat: @place.latitude, lng: @place.longitude, info_window_html: render_to_string(partial: "info_window", locals: {place: @place}) }]
  end

  def new
    @place = Place.new
    authorize @place
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    @place.save!
    @tags = PlaceTag.where(id: params[:place][:place_tag_ids])
    @place.place_tags << @tags
    @type_tags = PlaceTravelerTypeTag.where(id: params[:place][:place_traveler_type_tag_ids])
    @place.place_traveler_type_tags << @type_tags

    # address = Geocoder.search([@place.longitude, @place.latitude]).first.address
    # @place.address = address

    if @place.save!
      redirect_to place_path(@place), notice: "Place was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
    authorize @place
  end

  def edit
  end

  def update
    @tags = PlaceTag.where(id: params[:place][:place_tag_ids])
    @place.place_tags << @tags

    @type_tags = PlaceTravelerTypeTag.where(id: params[:place][:place_traveler_type_tag_ids])
    @place.place_traveler_type_tags << @type_tags

    if @place.update(place_params)
      redirect_to place_path(@place), notice: "Place was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place.destroy
    redirect_to secret_spots_path, status: :see_other, notice: "Place was successfully destroyed."
  end

  private

  def set_place
    @place = Place.find(params[:id])
    authorize @place
  end

  def place_params
    params.require(:place).permit(:name, :description, :address, :price, :duration, :min_temp, :max_temp, :photos, :secret_spot, :touristic, :longitude, :latitude, :validation, :place_traveler_type_tags, :place_tags, :place_taggings, :place_trav_taggings, :validation, place_traveler_type_tag_ids:[], place_tag_ids:[])
  end
end

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="containersecretspot">
    <div class="titre">
      <h1>Mon Secret Spot 🤭</h1>
    </div>

    <div class="form-inputs">
      <%= f.label :nom %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-inputs">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control", minlength: 10, maxlength: 400 %>
   <div id="description-error" style="color: red;"></div>
</div>

  <script>
    const descriptionInput = document.querySelector('#<%= f.object_name %>\\_description');
    const descriptionError = document.querySelector('#description-error');

    descriptionInput.addEventListener('input', function() {
      if (descriptionInput.validity.tooShort) {
        descriptionError.textContent = 'Veuillez saisir au moins 10 caractères.';
      } else if (descriptionInput.validity.tooLong) {
        descriptionError.textContent = 'Veuillez ne pas dépasser 400 caractères.';
      } else {
        descriptionError.textContent = '';
      }
    });
  </script>

    <div class="form-inputs">
      <%= f.label :prix_par_personne %>
      <%= f.text_field :price, class: "form-control", pattern: "[0-9]*" %>
  <div id="price-error" style="color: red;"></div>
</div>

  <script>
    const priceInput = document.querySelector('#<%= f.object_name %>\\_price');
    const priceError = document.querySelector('#price-error');

    priceInput.addEventListener('input', function() {
      if (!priceInput.checkValidity()) {
        priceError.textContent = 'Veuillez saisir un numéro valide.';
      } else {
        priceError.textContent = '';
      }
    });
  </script>

    <div class="form-inputs">
      <%= f.label :durée %>
      <p class="d-flex"><%= f.text_field :duration, class: "form-control", placeholder: "ex: 120" %>  min</p>
    </div>

    <div class="accessible">
      <div class="accessibleby">
        <div class="form-inputs">
          <%= f.label :accessible_dès, placeholder: "20"%>
          <p class="d-flex w-45"><%= f.text_field :min_temp, class: "form-control", placeholder: "ex:20" %>°C</p>
        </div>
      </div>

      <div class="accessibleuntil">
        <div class="form-inputs">
          <%= f.label :jusqu_à %>
          <p class="d-flex w-45"><%= f.text_field :max_temp, class: "form-control", placeholder: "ex :35" %>°C</p>
        </div>
      </div>
    </div>

    <div class="form-inputs">
      <%= f.input :photos, as: :file %>
      <%# <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    </div>

    <%# <div class="form-inputs"> %>
      <%# <%= f.input :address, class: "form-control" %>
    <%# </div> %>


    <%= f.input :address,
      label: "adresse",
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY_NASTYA"]}} %>

    <%# <div>
      <input type="checkbox" id="map-style-checkbox" class="d-none" />
      <label for="map-style-checkbox"><i class="fa-solid fa-layer-group layer"></i></label>
    </div> %>

    <%# <div %>
      <%# data-controller="carte" %>
      <%# data-carte-markers-value="<%= @markers.to_json %>
      <%# data-carte-api-key-value="<%= ENV['MAPBOX_API_KEY_NASTYA'] %>
    <%# > %>
      <%# <div style="width: 100%; height: 500px;" data-carte-target="map"></div> %>
      <%# <input  id="latitude" name="place[latitude]" data-carte-target="latitude" class="d-none"> %>
      <%# <input  id="longitude" name="place[longitude]" data-carte-target="longitude"> %>
      <%# <input  id="address" name="place[address]" data-carte-target="address" > %>
    <%# </div> %>



    <% if policy(@place).admin? %>
       <div>
          <%= f.association :place_traveler_type_tags, collection: PlaceTravelerTypeTag.all, label: "Place Tags :", as: :check_boxes, label_method: :tag, value_method: :id, input_html: { class: "trav-selector-tag d-none" }, include_hidden: false, multiple: true, item_wrapper_class: 'tag-item' %>
      </div>
    <% end %>

    <% if policy(@place).admin? %>
      <div>
        <%= f.association :place_tags, collection: PlaceTag.all, label: "Place Tags :", prompt:"salut", as: :check_boxes, input_html: { class: "selector-tag d-none" }, include_hidden: false, multiple: true, item_wrapper_class: 'tag-item' %>
      </div>
    <% end %>

    <% if policy(@place).admin? %>
      <div class="form-inputs">
        <%= f.input :secret_spot, collection: ["true", "false"], class: "form-control d-flex", label: "Secret Spot" %>

      </div>
    <% end %>

    <% if policy(@place).admin? %>
      <div class="form-inputs">
        <%= f.input :touristic, collection: ["true", "false"], class: "form-control d-flex", label: "Touristique" %>
      </div>
    <% end %>
    <% if policy(@place).admin? %>
      <div class="form-inputs">
        <%= f.input :validation, collection: ["true", "false"], class: "form-control d-flex", label: "Validation" %>
      </div>
    <% end %>
    <%# <div>
      <%# f.button :submit, class: "btn-cr form-actions", label: "Créer mon Secret Spot"%>
    <%# </div> %>
    <div class="creation">
      <%= submit_tag "Créer mon secret spot", class: "create_btn" %>
    </div>
  </div>
<% end %>

app/views/places/_form_edit.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="containersecretspot">
    <div class="titre">
      <h1>Mon Secret Spot 🤭</h1>
    </div>

    <div class="form-inputs">
      <%= f.label :nom %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-inputs">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control", minlength: 10, maxlength: 400 %>
   <div id="description-error" style="color: red;"></div>
</div>

  <script>
    const descriptionInput = document.querySelector('#<%= f.object_name %>\\_description');
    const descriptionError = document.querySelector('#description-error');

    descriptionInput.addEventListener('input', function() {
      if (descriptionInput.validity.tooShort) {
        descriptionError.textContent = 'Veuillez saisir au moins 10 caractères.';
      } else if (descriptionInput.validity.tooLong) {
        descriptionError.textContent = 'Veuillez ne pas dépasser 400 caractères.';
      } else {
        descriptionError.textContent = '';
      }
    });
  </script>

    <div class="form-inputs">
      <%= f.label :prix_par_personne %>
      <%= f.text_field :price, class: "form-control", pattern: "[0-9]*" %>
  <div id="price-error" style="color: red;"></div>
</div>

  <script>
    const priceInput = document.querySelector('#<%= f.object_name %>\\_price');
    const priceError = document.querySelector('#price-error');

    priceInput.addEventListener('input', function() {
      if (!priceInput.checkValidity()) {
        priceError.textContent = 'Veuillez saisir un numéro valide.';
      } else {
        priceError.textContent = '';
      }
    });
  </script>

    <div class="form-inputs">
      <%= f.label :durée %>
      <p class="d-flex"><%= f.text_field :duration, class: "form-control", placeholder: "ex: 120" %>  min</p>
    </div>

    <div class="accessible">
      <div class="accessibleby">
        <div class="form-inputs">
          <%= f.label :accessible_dès, placeholder: "20"%>
          <p class="d-flex w-45"><%= f.text_field :min_temp, class: "form-control", placeholder: "ex:20" %>°C</p>
        </div>
      </div>

      <div class="accessibleuntil">
        <div class="form-inputs">
          <%= f.label :jusqu_à %>
          <p class="d-flex w-45"><%= f.text_field :max_temp, class: "form-control", placeholder: "ex :35" %>°C</p>
        </div>
      </div>
    </div>

    <div class="form-inputs">
      <%= f.input :photos, as: :file %>
      <%# <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    </div>

    <div class="form-inputs">
      <%= f.input :address, class: "form-control" %>
    </div>


      <%# <%= f.input :address,
      # label: "adresse",
      # input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      # wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY_NASTYA"]}}%>


    <%# <h3 class="address">Address*</h4> %>
   <%# <div>
    <button id="map-style-btn"><i class="fa-solid fa-layer-group layer"></i></button>
      </div> %>
    <%# <div>
      <button id="map-style-toggle"><i class="fas fa-toggle-on fa-lg"></i></button>
    </div> %>
    <div>
      <input type="checkbox" id="map-style-checkbox" class="d-none" />
      <label for="map-style-checkbox"><i class="fa-solid fa-layer-group layer"></i></label>
    </div>
<%#
      <label for="map-style">Toggle Map Style</label>
      <input id="map-style">
      <select id="style-select">
        <option value="streets">Streets</option>
        <option value="satellite">Satellite</option>
      </select>
    </div> %>




    <%# <div %>
      <%# data-controller="carte" %>
      <%# data-carte-markers-value="<%= @markers.to_json %>
      <%# data-carte-api-key-value="<%= ENV['MAPBOX_API_KEY_NASTYA'] %>
    
      <%# <div style="width: 100%; height: 500px;" data-carte-target="map"></div> %>
      <%# <input  id="latitude" name="place[latitude]" data-carte-target="latitude" class="d-none"> %>
      <%# <input  id="longitude" name="place[longitude]" data-carte-target="longitude" class="d-none"> %>
      <%# <input  id="address" name="place[address]" data-carte-target="address" class="d-none"> %>
  <%# </div> %>



    <% if policy(@place).admin? %>
       <div>
          <%= f.association :place_traveler_type_tags, collection: PlaceTravelerTypeTag.all, label: "Place Tags :", as: :check_boxes, label_method: :tag, value_method: :id, input_html: { class: "trav-selector-tag d-none" }, include_hidden: false, multiple: true, item_wrapper_class: 'tag-item' %>
      </div>
    <% end %>

    <% if policy(@place).admin? %>
      <div>
        <%= f.association :place_tags, collection: PlaceTag.all, label: "Place Tags :", prompt:"salut", as: :check_boxes, input_html: { class: "selector-tag d-none" }, include_hidden: false, multiple: true, item_wrapper_class: 'tag-item' %>
      </div>
    <% end %>

    <% if policy(@place).admin? %>
      <div class="form-inputs">
        <%= f.input :secret_spot, collection: ["true", "false"], class: "form-control d-flex", label: "Secret Spot" %>

      </div>
    <% end %>

    <% if policy(@place).admin? %>
      <div class="form-inputs">
        <%= f.input :touristic, collection: ["true", "false"], class: "form-control d-flex", label: "Touristique" %>
      </div>
    <% end %>
    <% if policy(@place).admin? %>
      <div class="form-inputs">
        <%= f.input :validation, collection: ["true", "false"], class: "form-control d-flex", label: "Validation" %>
      </div>
    <% end %>

    <%# <div>
      <%# f.button :submit, class: "btn-cr form-actions", label: "Créer mon Secret Spot"%>
    <%# </div> %>
    <div class="creation">
      <%= submit_tag "Créer mon secret spot", class: "create_btn" %>
    </div>
  </div>
<% end %>

app/views/places/_form_new.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="containersecretspot">
    <div class="titre">
      <h1>Mon Secret Spot 🤭</h1>
    </div>

    <div class="form-inputs">
      <%= f.label :nom %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-inputs">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
    </div>

    <div class="form-inputs">
      <%= f.label :prix_par_personne %>
      <%= f.text_field :price, class: "form-control" %>
    </div>

    <div class="form-inputs">
      <%= f.label :durée %>
      <p class="d-flex"><%= f.text_field :duration, class: "form-control", placeholder: "ex: 120" %>min</p>
    </div>

    <div class="accessible">
      <div class="accessibleby">
        <div class="form-inputs">
          <%= f.label :accessible_dès, placeholder: "20"%>
          <p class="d-flex w-45"><%= f.text_field :min_temp, class: "form-control", placeholder: "ex: 20" %>°C</p>
        </div>
      </div>

      <div class="accessibleuntil">
        <div class="form-inputs">
          <%= f.label :jusqu_à %>
          <p class="d-flex w-45"><%= f.text_field :max_temp, class: "form-control", placeholder: "ex :35" %>°C</p>
        </div>
      </div>
    </div>

    <div class="form-inputs">
      <%= f.input :photos, as: :file %>
    </div>

    <%# <div class="form-inputs"> %>
      <%# <%= f.label :addresse %>
      <%# <%= f.text_field :address, class: "form-control" %>
    <%# </div> %>

    <div class="form-inputs">
      <%= f.input :address,
      label: "adresse",
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
    </div>



     <%# <div>
      <%= f.button :submit, class: "btn-cr form-actions"%>
    <%# </div> %>

  <div>
    <%= submit_tag "Crée ton secret spot", class: "create_btn"%>
  </div>
</div>

<% end %>

app/views/places/_info_window.html.erb
<%= link_to place_path(place), class: "travel-card" do %>
  <div class="popup-card">
    <% if place.photos.attached? %>
      <%= cl_image_tag place.photos.first.key, height: 450, width: 450, crop: :fill, class: "img-rec" %>
    <% else %>
      <img src="https://images.adsttc.com/media/images/5d44/14fa/284d/d1fd/3a00/003d/large_jpg/eiffel-tower-in-paris-151-medium.jpg?1564742900" alt="Image 2" style="width: 60px; height: 60px;" >
    <% end %>
    <div>
      <h2 class="popup-title"><%= place.name %></h2>
      <p class="popup-title"><%= place.description.first(50)... %></p>
    </div>
  </div>
<% end %>

app/views/places/edit.html.erb
<%= render "form_edit", place: @place %>

<br>

<div>
  <%= link_to "Show this place", @place %> |
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/index.html.erb
<h1>En Attente de validation 🤔</h1>

<div id="places">
  <div class="index-grid places-card">
    <% @places.each do |place| %>
  <%= link_to place_path(place), class: "travel-card" do %>
      <div class="rectangle">
          <% if place.photos.attached? %>
            <% place.photos.each do |photo| %>
              <%= cl_image_tag photo.key, height: 350, width: 450, crop: :fill %>
              <% break %>
            <% end %>
          <% end %>
          <div>
            <h2><%= place.name %></h2>
            <% if place.validation? %>
              <%= place.description.first(75).. %>
            <% else %>
              <h3>En attente de validation</h3>
            <% end %>
          </div>
      </div>
  <% end %>
<% end %>
    <div style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>
<%# <%= link_to "Nouvelle place", new_place_path %> 

app/views/places/new.html.erb
<%= render "form", place: @place %>

<br>

<%# <div>
  <%= link_to "Back to places", places_path %>
<%# </div> %>

app/views/places/show.html.erb
<div id="carouselExampleIndicators" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>

  <div class="carousel-inner">
    <% @place.photos.each_with_index do |photo, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
        <%= cl_image_tag photo.key, height: 450, width: 450, crop: :fill, class: "d-block w-100" %>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="grey-box">
<h1 class="name"><%= @place.name %></h1>
<div class="d-flex align-content-center icons-box">
  <i class="fa-solid fa-clock place"></i> <%= @place.duration %>min</h3>
  <i class="fa-solid fa-temperature-three-quarters place"></i> <%= @place.min_temp %> to <%= @place.max_temp %> °C</h3>
  <% if @place.price > 0 %>
    <i class="fa-solid fa-money-bill place"></i> <%= @place.price %>€
  <% else %>
    <i class="fa-solid fa-money-bill place"></i> Gratuit
  <% end %>
</div>



<div class="address">
  <% if @place.address %>
    <h3 class="place-caracteristiques">Address : <%= @place.address.split(",").first(5).join(' ') %></h3>
  <% end %>
</div>
<p class="text-justify"><%= truncate(@place.description, length: 400) %></p>
</div>

<div class="map" style="width: 96%; height: 400px;"
  data-controller="map"
  data-map-markers-value="<%= @marker.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div id="buttons">
  <%= link_to "Retourner à la liste", dashboards_path, class: "button-back" %>
  <%# <br> %>

  <% if policy(@place).update? %>
    <%= link_to "Modifier", edit_place_path(@place), class: "button-back" %>
  <% end %>
    <%# <%= link_to "Destroy", @place, method: :delete, class: "button-back" %>
  <% if policy(@place).destroy? %>
    <%= link_to "Supprimer", place_path(@place), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "button-back" %>
  <% end %>
</div>