config/routes.rb
Rails.application.routes.draw do
  root to: "pages#dashboard"
  get "dashboards", to: "pages#dashboard"
  get "past_dashboards", to: "pages#past_dashboard"
  get "secret_spots", to: "pages#secret_spot"
  devise_for :users

  resources :travels
  resources :travel_tags, only: [:new, :create]
  resources :trav_trav_type_tags, only: [:new, :create]

  resources :places
  resources :place_traveler_type_tags, only: [:index, :new, :create, :destroy]
  resources :place_tags, only: [:index, :new, :create, :destroy]

  get "travels/:id/map", to: "travels#map", as: :travel_map

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.erb
<div class="navbar-down fixed-bottom">
    <ul class="navbar-down d-flex justify-content", id="down">
      <%= link_to dashboards_path, class: "nav-item active navbar-titre" do%>
        <li>
          <i class="fa-solid fa-user"></i>
          <p class= "navbar-titre" style= "margin: 0", id= "romain">Mon Profil</p>
        </li>
      <% end %>
        <div class="vl"></div>

        <%= link_to new_travel_path, class: "nav-item active navbar-titre" do%>
        <li>
          <i class="fa-regular fa-map"></i>
          <p class= "navbar-titre" style= "margin: 0", id= "romain">Nouveau Voyage</p>
        </li>
        <% end %>
        <div class="vl"></div>

        <%= link_to new_place_path, class: "nav-item active navbar-titre" do%>
        <li>
              <i class="fa-solid fa-plus"></i>
            <p class= "navbar-titre" style= "margin: 0", id= "romain">Secret Spot</p>
        </li>
          <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ROAMLY</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "favicon.ico", rel: "icon", type: "image/ico" %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
     <%= render 'shared/ios_pwa_links' %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%# <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"> %>
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_green.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">

    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.js"></script>

    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.css" type="text/css">
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
  </head>


  <body>

    <%# <p class="notice"><%= notice %>
    <%# <p class="alert"><%= alert %>
    <%= render "shared/navbar" %>
      <%= yield %>
    <%= render "layouts/footer" %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>

  </body>
</html>